<a href="https://colab.research.google.com/github/Soumya1219/Data-Science-1stop-AI-/blob/main/Detection%20of%20Parkinson%20Disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **DETECTION OF PARKINSON DISEASE**

In [1]:
pip install numpy pandas sklearn xgboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0.post1-py3-none-any.whl size=2955 sha256=e819e91356b7560b2bf741138e10206b00d2d0676dcd1290d294c526795d45df
  Stored in directory: /root/.cache/pip/wheels/f8/e0/3d/9d0c2020c44a519b9f02ab4fa6d2a4a996c98d79ab2f569fa1
Successfully built sklearn


### **Import required libraries**

In [2]:

import numpy as np
import pandas as pd

In [3]:
# Read the data
my_data = pd.read_csv("https://raw.githubusercontent.com/chaitanyabaranwal/ParkinsonAnalysis/master/parkinsons.csv")
my_data

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0    phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1    phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2    phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3    phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4    phon_R01_S01_5      116.014       141.781       110.655         0.01284   
..              ...          ...           ...           ...             ...   
190  phon_R01_S50_2      174.188       230.978        94.261         0.00459   
191  phon_R01_S50_3      209.516       253.017        89.488         0.00564   
192  phon_R01_S50_4      174.688       240.005        74.287         0.01360   
193  phon_R01_S50_5      198.764       396.961        74.904         0.00740   
194  phon_R01_S50_6      214.289       260.277        77.973         0.00567   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0             0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1             0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2             0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3             0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4             0.00011   0.00655   0.00908     0.01966       0.06425  ...   
..                ...       ...       ...         ...           ...  ...   
190           0.00003   0.00263   0.00259     0.00790       0.04087  ...   
191           0.00003   0.00331   0.00292     0.00994       0.02751  ...   
192           0.00008   0.00624   0.00564     0.01873       0.02308  ...   
193           0.00004   0.00370   0.00390     0.01109       0.02296  ...   
194           0.00003   0.00295   0.00317     0.00885       0.01884  ...   

     Shimmer:DDA      NHR     HNR      RPDE       DFA   spread1   spread2  \
0        0.06545  0.02211  21.033  0.414783  0.815285 -4.813031  0.266482   
1        0.09403  0.01929  19.085  0.458359  0.819521 -4.075192  0.335590   
2        0.08270  0.01309  20.651  0.429895  0.825288 -4.443179  0.311173   
3        0.08771  0.01353  20.644  0.434969  0.819235 -4.117501  0.334147   
4        0.10470  0.01767  19.649  0.417356  0.823484 -3.747787  0.234513   
..           ...      ...     ...       ...       ...       ...       ...   
190      0.07008  0.02764  19.517  0.448439  0.657899 -6.538586  0.121952   
191      0.04812  0.01810  19.147  0.431674  0.683244 -6.195325  0.129303   
192      0.03804  0.10715  17.883  0.407567  0.655683 -6.787197  0.158453   
193      0.03794  0.07223  19.020  0.451221  0.643956 -6.744577  0.207454   
194      0.03078  0.04398  21.209  0.462803  0.664357 -5.724056  0.190667   

           D2       PPE  status  
0    2.301442  0.284654       1  
1    2.486855  0.368674       1  
2    2.342259  0.332634       1  
3    2.405554  0.368975       1  
4    2.332180  0.410335       1  
..        ...       ...     ...  
190  2.657476  0.133050       0  
191  2.784312  0.168895       0  
192  2.679772  0.131728       0  
193  2.138608  0.123306       0  
194  2.555477  0.148569       0  

[195 rows x 24 columns]

In [4]:
# Get the features
features = my_data.loc[: , my_data.columns != 'status'].values[: ,1:]
features

array([[119.992, 157.302, 74.997, ..., 0.266482, 2.301442, 0.284654],
       [122.4, 148.65, 113.819, ..., 0.33559, 2.486855, 0.368674],
       [116.682, 131.111, 111.555, ..., 0.311173, 2.342259, 0.332634],
       ...,
       [174.688, 240.005, 74.287, ..., 0.158453, 2.679772, 0.131728],
       [198.764, 396.961, 74.904, ..., 0.207454, 2.138608, 0.123306],
       [214.289, 260.277, 77.973, ..., 0.190667, 2.555477, 0.148569]],
      dtype=object)

In [5]:
# Get the labels
labels = my_data.loc[: ,'status'].values
labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# Get the count of label'1'
labels[labels ==1].shape[0]

147

In [7]:
# Get the count of label'0'
labels[labels ==0].shape[0]

48

In [8]:
from sklearn.preprocessing import MinMaxScaler

In [9]:
# Scale the features between -1 and 1
scaler = MinMaxScaler((-1,1))
x = scaler.fit_transform(features)
y = labels

In [10]:
x

array([[-0.63138346, -0.77481654, -0.89037042, ...,  0.17153026,
        -0.21867743, -0.0053808 ],
       [-0.6033463 , -0.81013911, -0.4433544 , ...,  0.48267409,
        -0.05370956,  0.34265204],
       [-0.66992292, -0.88174367, -0.46942324, ...,  0.37274182,
        -0.18236124,  0.19336492],
       ...,
       [ 0.00546073, -0.43717403, -0.89854572, ..., -0.31484696,
         0.11793486, -0.63884033],
       [ 0.28578581,  0.20361309, -0.89144127, ..., -0.09423055,
        -0.36355605, -0.67372646],
       [ 0.46654868, -0.35441175, -0.85610326, ..., -0.16981039,
         0.00734563, -0.5690805 ]])

In [11]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# Split the dataset into training and testing data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.33, random_state = 42)

In [13]:
x_train

array([[-0.64228163, -0.9058228 , -0.75452232, ...,  0.11942533,
        -0.02749361, -0.22262172],
       [-0.56561023, -0.84109332, -0.41425726, ...,  0.14451205,
         0.39490041,  0.35212539],
       [-0.03700254, -0.5665595 , -0.88456711, ..., -0.00947956,
         0.0377967 , -0.57391038],
       ...,
       [-0.30210977, -0.74343366, -0.11542137, ..., -0.63276672,
        -0.18051327, -0.41200593],
       [-0.30361176, -0.78020556, -0.19899363, ...,  0.05624028,
         0.26504047, -0.38615408],
       [-0.40745872,  0.97769681, -0.99215862, ...,  0.19025526,
         0.12785092,  0.65787817]])

In [14]:
x_test

array([[-0.72165429, -0.9001235 , -0.55532143, ...,  0.34951454,
        -0.11385722, -0.3179683 ],
       [-0.34966118,  0.00886535, -0.80093728, ...,  0.05123824,
        -0.25154502, -0.28079979],
       [-0.65609063, -0.89710238, -0.65251534, ..., -0.0921595 ,
        -0.09575651, -0.33012584],
       ...,
       [-0.43421512, -0.76434878, -0.24234573, ..., -0.34023984,
        -0.45015455, -0.61073923],
       [ 0.21902289, -0.56416302, -0.82934356, ...,  0.22644461,
         0.05474343, -0.41540673],
       [ 0.1145239 , -0.61463609,  0.16873352, ..., -0.74274851,
        -0.16521344, -0.70510824]])

In [15]:
y_train

array([1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1])

### **Training the Model**

In [16]:

from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(x_train,y_train)
y_pred = xgb.predict(x_test)

### **Accuracy of the Model**

In [17]:

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9538461538461539

In [18]:
from sklearn.metrics import accuracy_score
round(accuracy_score(y_test, y_pred),4)*100

95.38